name: Code Quality
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install black
      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Code Formatting with Black
        run: |
          black . --check --verbose

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package
        uses: actions/upload-release-asset@v1
        with:
          name: django_createdb-${{ github.ref }}.tar.gz
          path: dist/django_createdb-${{ github.ref }}.tar.gz
          content_type: application/gzip
